name: WorldProtection
author: Maxlego08
main: fr.maxlego08.worldprotection.WorldProtectionPlugin
website: https://groupez.dev
description: Protect your server !
version: 1.0.0
api-version: 1.13
commands: